name: iOS Unit Tests Only

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: macos-14
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode 16.4
        run: sudo xcode-select -s /Applications/Xcode_16.4.app/Contents/Developer

      - name: Show Xcode version
        run: xcodebuild -version

      - name: Build and Test (Unit Tests Only)
        run: |
          xcodebuild clean test \
            -project Coles.xcodeproj \
            -scheme Coles \
            -destination 'platform=iOS Simulator,name=iPhone 16' \
            -only-testing:ColesTests \
            -resultBundlePath TestResults/unit-tests.xcresult \
            CODE_SIGNING_ALLOWED=NO \
            ONLY_ACTIVE_ARCH=YES
        timeout-minutes: 10

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: TestResults/
          retention-days: 7

